
image:
  file: .gitpod.Dockerfile

tasks:
  - init: cabal update && cabal install unordered-containers

vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell
    - hoovercj.haskell-linter
